---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicada-sense-review-appspr-2 # Will be updated by deploy workflow
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/application-repository: cicada-sense
    argocd.argoproj.io/environment: "review"
    argocd.argoproj.io/deployment-id: "5327980533"
  labels:
    layer: applications
    service: cicada-sense
    component: main
    environment: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: cicada-sense-review-appspr-2 # Will be updated by deploy workflow
    server: https://192.168.200.101:443
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: ghcr.io/annoying-anemone/cicada-sense/charts/application
      targetRevision: "0.0.0-pr-2-7448a06" # Will be updated by deploy workflow
      chart: cicada-sense
      helm:
        values: |
          backend:
            ingress:
              hosts:
                - host: pr-2-cicada-sense-review.user-00.hoverkraft.cloud # Will be updated by deploy workflow
          frontend:
            ingress:
              hosts:
                - host: pr-2-cicada-sense-review.user-00.hoverkraft.cloud # Will be updated by deploy workflow
          live-data-generator:
            api:
              ingress:
                hosts:
                  - host: cicada-sense-generator-review.user-00.hoverkraft.cloud # Will be updated by deploy workflow
            ui:
              ingress:
                hosts:
                  - host: cicada-sense-generator-review.user-00.hoverkraft.cloud # Will be updated by deploy workflow
          deploymentId: "5327980533"
